version: '3.5'

services:

    educapi:
        container_name: educapi
        build:
            context: .
        restart: always
        ports:
            - "8080:8080"
        networks:
            - educapi-network
        depends_on:
            - db
        env_file: 
            - .env-prod



    db:
        container_name: postgres-educapi
        image: postgres:12.3
        restart: always
        networks:
            - educapi-network
        volumes:
            - postgres-educapi:/data/postgres
        env_file: 
            - .env-prod
        environment:
            POSTGRES_USER: DB_USER
            POSTGRES_PASSWORD: DB_PASSWORD
            POSTGRES_DB: DB_DATABASE
            PGDATA: /data/postgres

volumes:
    postgres-educapi:

networks: 
    educapi-network:
        driver: bridge
