version: '3.5'

services:

    educapi:
        container_name: educapi
        image: a4sufpb/educapi:${EDUCAPI_VERSION}
        restart: always
        ports:
            - "8080:8080"
        networks:
            - educapi-network
        depends_on:
            - db
        env_file: 
            - .env-prod

    db:
        container_name: postgres-educapi
        image: postgres:12.3
        restart: always
        networks:
            - educapi-network
        volumes:
            - educapi: /var/lib/postgresql/data
        env_file: 
            - .env-prod
        environment:
            POSTGRES_USER: DB_USER
            POSTGRES_PASSWORD: DB_PASSWORD
            POSTGRES_DB: DB_DATABASE
            PGDATA: /var/lib/postgresql/data/pgdata

volumes:
    educapi:

networks: 
    educapi-network:
        driver: bridge
