version: '3.5'

services:

    educapi:
        container_name: educapi
        build:
            context: .
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - db
        env_file:
            - .env

    db:
        container_name: postgres-educapi
        image: postgres:12.3
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - postgres-educapi:/data/postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /data/postgres
        env_file:
            - .env

volumes:
    postgres-educapi:

