name: Check deployment on Heroku

on:
  schedule:
  - cron: '0 12,22 * * *'
    

jobs:
  check-heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: ScholliYT/Broken-Links-Crawler-Action@v2.1.1
      with:
        website_url: 'http://educapi-a4sufpb.herokuapp.com'
        verbose: 'true' 
        max_retry_time: 240
        max_retries: 5
